language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t herbearth/dock-react -f Dockerfile.dev .

script:
  - docker run -e CI=true herbearth/dock-react npm run test -- --coverage